[package]
name = "horology-kernel"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["MINOOTS Engineering"]
description = "Durable timer scheduler core for the MINOOTS platform"
build = "build.rs"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
prost = "0.12"
prost-types = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.36", features = ["macros", "rt-multi-thread", "time", "sync", "signal"] }
tokio-stream = { version = "0.1", features = ["sync"] }
tonic = { version = "0.10", features = ["transport"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
uuid = { version = "1.7", features = ["v4", "serde"] }

[build-dependencies]
tonic-build = "0.10"
